### ISSUE TITLE
Add project description and other docs

### ISSUE THREAD

**Issue by zerothi** [pfebrer/sisl-gui#2]
The item
https://pypi.org/project/sisl-gui/

is rather empty. It may be nice to add some docs information.

**Comment by pfebrer** [comment]
Yeees! Do you know why the description here isn't used:

https://github.com/pfebrer/sisl-gui/blob/fd8dcac882c2b69d708de6052f1e27072d903348/setup.cfg#L1-L8

? I will try to post the README.md there too but first I wanted to understand why it ignores my description :(

**Comment by zerothi** [comment]
I think it needs to be `long_description`, in my `setup.py` I read in the md file and convert it

**Comment by zerothi** [comment]
Also, it doesn't ignore your description. It is the "title" description.

**Comment by pfebrer** [comment]
Yes, I realized just now these two things :sweat_smile:, thanks!
